@url = http://localhost:2121


###
GET {{url}}/list

###
POST {{url}}/signup
content-type: application/json


{
    "Title": "Wed, 21 Oct 2015 18:27:50 GMT",
   

}

###


# POST {{url}}/recipe/createRecipe


# content-type: application/json

# {
#     "name": "Wed, 21 Oct 2015 18:27:50 GMT",
   
# }