# @url = http://localhost:2121
@url = https://sustainable-hub-backend.herokuapp.com


###
GET {{url}}/list


###
GET {{url}}/login

###
# POST {{url}}/signup
# content-type: application/json


# {
#     "Title": "Wed, 21 Oct 2015 18:27:50 GMT",
   

# }

###

POST {{url}}/signup



{
   
  "user": "user"
   

}


###


# POST {{url}}/recipe/createRecipe


# content-type: application/json

# {
#     "name": "Wed, 21 Oct 2015 18:27:50 GMT",
   
# }